.clang-format, .travis.yml, Gemfile, Gemfile.lock, Rakefile, benchmarks/benchmarking_support.rb, benchmarks/bm_panko_json.rb, benchmarks/setup.rb, benchmarks/type_casts/bm_active_record.rb, benchmarks/type_casts/bm_panko.rb, benchmarks/type_casts/bm_pg.rb, benchmarks/type_casts/support.rb, ext/panko/attributes_iterator.c, ext/panko/attributes_iterator.h, ext/panko/extconf.rb, ext/panko/panko.c, ext/panko/type_cast.c, ext/panko/type_cast.h, lib/panko.rb, lib/panko/attributes/base.rb, lib/panko/attributes/field.rb, lib/panko/attributes/relationship.rb, lib/panko/serializer.rb, lib/panko/version.rb, panko.gemspec, spec/array_serializer_spec.rb, spec/models.rb, spec/serializer_spec.rb, spec/spec_helper.rb, spec/type_cast_spec.rb
After some thinking, I decided to re-write panko in native c.
Why? I needed bigger performance improvement on real workload.
In this pull request, those are the huge changes:
- Only field attributes are serialized in native
- Instead of reading attributes from ActiveRecord object like `person.name`, I am peeking into internal structures and doing all my typecasting my self.
If you read the last change carefully, you will ask **why?**, the reason is: ActiveRecord is designed to return objects in order to manipulate them - read them, change them, save them - all the happy mutations
For example, string type casting in ActiveRecord creates new string - why? I think because of safety reasons (mutations for example), while in panko - in the whole serialization "pipeline", I don't mutate any …
=> Native Implementation

ext/panko_serializer/attributes_iterator.c, ext/panko_serializer/attributes_iterator.h, ext/panko_serializer/panko_serializer.c, ext/panko_serializer/serialization_descriptor.c, ext/panko_serializer/serialization_descriptor.h, lib/panko/serialization_descriptor.rb, lib/panko/serializer.rb, spec/serializer_spec.rb
When serializers implement alias with method attributes, it get direct hit
on performance (becuase all type casting don't go through panko).
Aliases, allow to supply alias to attributes, for example:
```ruby
class FooWithAliasesSerializer < Panko::Serializer
attributes :address
aliases name: :full_name end
end
```
=> Aliases support

.gitignore, benchmarks/type_casts/bm_active_record.rb, benchmarks/type_casts/bm_panko.rb, ext/panko_serializer/attributes_iterator.c, ext/panko_serializer/type_cast.c, spec/type_cast_spec.rb
- Adapting attributes reading to @attributes being a hash a not a LazyAttributeHash
- Typecasting: use `deserialize` if available, otherwise `type_cast_from_database` 
Rails 5.1
```
{"label":"Panko_SimpleWithMethodCall_Posts_2300","ips":"74.41","allocs":"4908/15"}
{"label":"Panko_SimpleWithMethodCall_Posts_50","ips":"4,164.64","allocs":"117/0"}
{"label":"Panko_HasOne_Posts_2300","ips":"45.66","allocs":"9216/0"}
{"label":"Panko_HasOne_Posts_50","ips":"3,083.36","allocs":"216/0"}
{"label":"Panko_Simple_Posts_2300","ips":"89.07","allocs":"4614/0"}
{"label":"Panko_Simple_Posts_50","ips":"5,517.12","allocs":"114/0"}
```
Rails 4.2
```
{"label":"Panko_SimpleWithMethodCall_Posts_2300","ips":"90.02","allocs":"4957/15"}
{"label":"Panko_SimpleWithMethodCall_Posts_50","ips":"4,613.35","allocs":"117/0" …
```
=> Rails 5 support

ext/panko_serializer/association.c, ext/panko_serializer/association.h, ext/panko_serializer/attribute.c, ext/panko_serializer/attribute.h, ext/panko_serializer/attributes_iterator.c, ext/panko_serializer/attributes_iterator.h, ext/panko_serializer/panko_serializer.c, ext/panko_serializer/panko_serializer.h, ext/panko_serializer/serialization_descriptor.c, ext/panko_serializer/serialization_descriptor.h, ext/panko_serializer/type_cast.c, ext/panko_serializer/type_cast.h, lib/panko/attribute.rb, lib/panko/serialization_descriptor.rb, lib/panko/serializer.rb, lib/panko_serializer.rb, spec/serializer_descriptor_spec.rb, spec/type_cast_spec.rb
* Refactoring attributes reading code, to be much more simpler - by
creating context and separate function for reading specific attribute
* Changing attribute & association to be backed behind C struct - for
performance improvement
* Unifying `aliases` and `fields` to `attributes`
* Caching type in attribute and invalidating it when the record class is
changed.
* Adding freeing code to SerializationDescription (and new structs)
=> Large refactor and performance improvements

lib/panko/serializer_resolver.rb
Because byebug is in the gemspec as a development dependency, requiring it here causes upstream apps to either fail to bundle or require byebug in production bundler groups.  Guessing it was left there by accident.
=> Remove byebug requirement from SerialResolver

docs/README.md
Small fix for a spelling error in the documentation's table of contents
=> Fix spelling mistake

Gemfile, Rakefile, benchmarks/bm_object_writer.rb, benchmarks/bm_to_object.rb, ext/panko_serializer/attributes_writer/active_record.c, ext/panko_serializer/common.h, ext/panko_serializer/serialization_descriptor/attribute.c, lib/panko/array_serializer.rb, lib/panko/attribute.rb, lib/panko/object_writer.rb, lib/panko/serializer.rb, lib/panko_serializer.rb, spec/panko/array_serializer_spec.rb, spec/panko/object_writer_spec.rb, spec/panko/response_spec.rb, spec/panko/serializer_spec.rb, spec/spec_helper.rb
Add native support for serializing to array of hashes, which improves performance.
Master:
```
{"label":"Panko_Simple_Posts_2300","ips":"94.99","allocs":"27757/14"}
{"label":"Panko_Simple_Posts_50","ips":"4,602.76","allocs":"621/0"}
{"label":"Panko_HasOne_Posts_2300","ips":"48.85","allocs":"41429/0"}
{"label":"Panko_HasOne_Posts_50","ips":"2,806.27","allocs":"929/0"}
```
This branch:
```
{"label":"Panko_Simple_Posts_2300","ips":"142.33","allocs":"4756/14"}
{"label":"Panko_Simple_Posts_50","ips":"6,429.52","allocs":"120/0"}
{"label":"Panko_HasOne_Posts_2300","ips":"68.87","allocs":"9228/0"}
{"label":"Panko_HasOne_Posts_50","ips":"3,447.5","allocs":"228/0"}
```
running with ruby 2.6.3
=> ObjectWriter suport

docs/associations.md, spec/panko/serializer_spec.rb
I was copying and pasting from the example code in the docs and got a runtime error. This patch fixes the the typo in three places.
=> Fix typo: serailizer -> serializer

lib/panko/serializer.rb, spec/panko/array_serializer_spec.rb, spec/panko/serializer_spec.rb, spec/spec_helper.rb
This causes `serialize` or `seriaize_to_json` to raise an `ArgumentError` if you try and serialize more than once with the same `Panko::Serializer` object.
Turned out to be a lot bigger than I expected as the `serialized_as` matcher actually uses the same serializer more than once as it uses both methods with the same object. I didn't know if would be a good idea to allow this case, as then you get in to object comparison issues?
I've updated `serialized_as` to accept either a serializer class name to build a simple serializer with no options, or a lambda, to build more complex serializer instances. This allows `serialized_as` to create new instances of the same serializer, as previously taking in an already created instance made this impossible.
fixes #47
=> [issue-47] Raise error if serializer is reused

ext/panko_serializer/attributes_writer/attributes_writer.c, ext/panko_serializer/attributes_writer/attributes_writer.h, ext/panko_serializer/attributes_writer/hash.c, ext/panko_serializer/attributes_writer/hash.h, spec/panko/serializer_spec.rb
If a `Hash` is passed as object, it will attempt to find attributes using `Hash#[]`. 
`PankoSerializer` must at some point turn `attributes :blah` from a `Symbol` to a `String`, as it only works with `String` keys. I think this is good enough as it'd be hard to detect which to use, and might cause confusion.
I attempted to make it work with `ActiveSupport::HashWithIndifferentAccess` but was unable to get the hash lookup working in ext
```ruby
it "hash (with indifferent access)" do
foo = ActiveSupport::HashWithIndifferentAccess.new(
"name" => Faker::Lorem.word,
"address" => Faker::Lorem.word
)
expect(foo).to serialized_as(FooSerializer,
"name" => foo[:name],
"address" => foo[:address])
end
```
```c
void hash_attributes_writer(VALUE obj, VALUE attributes,
EachAttributeFunc func, VALUE …
```
=> [issue-48] Ability to serialize a hash object

benchmarks/bm_panko_json.rb, benchmarks/setup.rb, benchmarks/type_casts/bm_panko.rb, ext/panko_serializer/attributes_writer/active_record.c, ext/panko_serializer/attributes_writer/common.h, ext/panko_serializer/attributes_writer/hash.c, ext/panko_serializer/attributes_writer/plain.c, ext/panko_serializer/attributes_writer/type_cast/type_cast.c, ext/panko_serializer/attributes_writer/type_cast/type_cast.h, ext/panko_serializer/panko_serializer.c, lib/panko/object_writer.rb, spec/panko/type_cast_spec.rb
Until this commit we took json strings out of db and did JSON.parse on
them.
This commit changes this to:
- Use `Oj.sc_parse` to validate that the string is valid JSON
- Use `Oj::StringWriter#push_json` to push the json string as is.
Benchmarks:
master:
```
{"label":"Panko_ActiveRecord_SimpleWithJson_Posts_2300","ips":"93.59","allocs":"29919/0"}
{"label":"Panko_ActiveRecord_SimpleWithJson_Posts_50","ips":"4,296.59","allocs":"669/0"}
```
this commit:
```
{"label":"Panko_ActiveRecord_SimpleWithJson_Posts_2300","ips":"146.93","allocs":"9219/0"}
{"label":"Panko_ActiveRecord_SimpleWithJson_Posts_50","ips":"6,650.14","allocs":"219/0"}
```
less allocations and faster!
=> Json Columns: performance improvements

lib/panko/response.rb, spec/panko/response_spec.rb
A small addition to allow for usage of context in Panko::Response.
Example
```ruby
context = { value: "something" }
response = Panko::Response.create do |t|
[
{
data: t.value(
foos: t.array_serializer(Foo.all, FooWithContextSerializer, context: context),
foo: t.serializer(Foo.first, FooWithContextSerializer, context: context)
)
}
]
end
```
Specially useful when using Panko::Response for single object serialization.
=> Add context to serializers in Panko::Response

.github/workflows/ruby.yml, ext/panko_serializer/attributes_writer/active_record.c, ext/panko_serializer/attributes_writer/attributes_writer.c, panko_serializer.gemspec
Drop support for EOL versions:
- Rails 4.2 is EOL
- Support only ruby 2.5
=> Rails 6.1.0 support

ext/panko_serializer/panko_serializer.c, lib/panko/serializer.rb, spec/panko/serializer_spec.rb
I'm trying to convert one of our app that uses AMS 0.9 (https://github.com/Shopify/shipit-engine/pull/1139), but one missing feature the the possibility of skipping an attribute.
I've read https://github.com/panko-serializer/panko_serializer/issues/16 and I understand the performance concern, however I think it can be done efficiently.
It define a special value `Panko::Serializer::SKIP`, if a serializer field returns it, the field is not serialized. The performance overhead should be totally negligible.
=> Allow to dynamically skip a field by returning SKIP

.github/workflows/ruby.yml, ext/panko_serializer/attributes_writer/attributes_writer.c, ext/panko_serializer/attributes_writer/type_cast/type_cast.c, ext/panko_serializer/serialization_descriptor/association.c, ext/panko_serializer/serialization_descriptor/attribute.c, spec/spec_helper.rb
Ruby 2.7 introduced GC compaction. This means that objects can me moved from on GC slot to another. Since then C extensions must declare all the `VALUE` they keep in global variables with `rb_global_variable`. This allow the GC to update the references held by C extensions.
Ruby 3.0 added `GC.verify_compaction_references` which makes it easier to test that all references are properly declared. All objects are moved to new heap pages, so after than any attempt to use undeclared global variable is extremly likely to segfault.
I simply declare all the global variables and add Ruby 3.0 to the test matrix.
=> Register global variables to the GC

lib/panko/serializer.rb, lib/panko/serializer_resolver.rb, panko_serializer.gemspec, spec/panko/serializer_resolver_spec.rb
I'm trying to convert one of our app that uses AMS 0.9 (Shopify/shipit-engine#1139), and one small issue I ran into is that Shipit is a Rails engine, as such all constants are namespaced under `Shipit::`.
So none of the automatic serializer resolution worked because it would look for e.g. `::UserSerializer` instead of `Shipit::UserSerializer`.
We simply first look for a serializer inside the namespace we're defining the relation, if not found we fallback to the top level namespace.
PS: thanks for the two very quick merges!
=> Respect namespacing in SerializerResolver

lib/panko/serializer.rb, spec/panko/serializer_spec.rb
This is a follow up to #108, and adds support for passing in `serializer` as a string in the `has_many` association.
=> Add support for passing serializer as string in has_many association

lib/panko/serializer.rb, lib/panko/serializer_resolver.rb, spec/models.rb, spec/panko/serializer_spec.rb
This PR allows has_one and has_many associations to use a different serializer than the association name, if a string is passed in for the serializer.
Using a real world example - If you have this defined: `has_one :current_driver, serializer: "User"` in a Vehicle, the serializer resolver will always look for `CurrentDriverSerializer`, which is not the correct serializer, because we wanted a `UserSerializer`.
=> Allow more flexibility in how serializers are resolved when strings are passed to the serializer option

ext/panko_serializer/serialization_descriptor/association.c, ext/panko_serializer/serialization_descriptor/attribute.c
When it invoked Data_Wrap_Struct(), Ruby's GC can release allocated memory properly. However, we have to manage the memory ourselves until invoking Data_Wrap_Struct().
Check_Type() will raise an exception if the argument is not a string, and memory leak will be caused by the exception.
So, I think ALLOC() should be called after Check_Type().
You will see an increase memory usage with attached test code.
```
0, 19.3828125 MB
5000, 20.19140625 MB
10000, 20.70703125 MB
15000, 21.22265625 MB
20000, 21.73828125 MB
25000, 22.25390625 MB
30000, 22.76953125 MB
```
```
0, 19.359375 MB
5000, 19.90234375 MB
10000, 19.90234375 MB
15000, 19.90234375 MB
20000, 19.90234375 MB
25000, 19.90234375 MB
30000, 19.90234375 MB
```
```ruby
require 'panko_serializer'
30_001.times do |i| …
```
=> Fix memory leak which caused by exception

ext/panko_serializer/panko_serializer.c, lib/panko/serializer.rb, spec/panko/serializer_spec.rb
`method_added` removes the same name attribute from `attributes` and add a new one to `method_fields`. It ignores `alias_name` of the original attribute.
Then the alias setting does not work with method fields.
With this patch, the original `alias_name` is kept.
In addition, `serialize_method_fields` does not use `attr_name_for_serialization` unlike other serialize functions. This patch also fixes it to use the function.
=> Keep alias_name when method_added (#135)

.github/workflows/docs.yml, .github/workflows/lint.yml, .github/workflows/ruby.yml
Due to EOL of Node12 on GitHub Actions, the following actions are to be updated:
- actions/checkout from v2 to v4
- actions/cache from v1 to v3
- webfactory/ssh-agent from v0.4.1 to v0.6.0
https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
=> ci: update all actions to utilize Node16 instead of Node12

.github/workflows/lint.yml, .github/workflows/ruby.yml, Gemfile
- Previous update: #110
https://rubyonrails.org/2023/10/5/Rails-7-1-0-has-been-released
=> chore: Rails 7.1 support by default

docs/docs/associations.md
Executing the code from this example:
```
posts = Post.all
Panko::ArraySerializer.new(posts, only: {
instance: [:title, :body, :author, :comments],
author: [:id],
comments: [:id],
})
```
raises an ArgumentError:
```
ArgumentError (
Please pass valid each_serializer to ArraySerializer, for example:
> Panko::ArraySerializer.new(posts, each_serializer: PostSerializer)
):
```
I have modified the code example to match the error's suggestion.
=> docs: clarify example in Nested Filters

benchmarks/type_casts/bm_panko.rb, ext/panko_serializer/attributes_writer/type_cast/type_cast.c, lib/panko/serializer.rb, lib/panko/version.rb
Add support for:
- ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Jsonb
- ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Timestamp
Benchmark - running `benchmarks/sanity` with ITEMS_COUNT of 2300, adding `jsonb` column to Posts.
```
Master:
{"label":"Panko_Simple_Posts_2300","ips":"87.56","allocs":"20721/2"}
{"label":"Panko_Simple_Posts_50","ips":"4,266.99","allocs":"469/2"}
{"label":"Panko_HasOne_Posts_2300","ips":"109.31","allocs":"9227/1"}
{"label":"Panko_HasOne_Posts_50","ips":"5,557.47","allocs":"227/1"}
{"label":"Panko_SimpleWithMethodCall_Posts_2300","ips":"82.25","allocs":"20722/2"}
{"label":"Panko_SimpleWithMethodCall_Posts_50","ips":"3,954.0","allocs":"472/2"}
Branch:
{"label":"Panko_Simple_Posts_2300","ips":"137.27","allocs":"9221/1"} …
```
=> Add fast-path for type-casting Jsonb/Timestamp

.github/dependabot.yml
I have seen on PR #174 that you have manually updated the GitHub Actions versions of the CI of this project.
This is something that could be automated with Dependabot :)
=> Configure Dependabot for automatic GitHub Actions updates

README.md
Hey, while researching Panko Serializer gem I have realized that documentation links in README are broken as they include `/docs/` in the URL, for example: https://panko.dev/docs/design-choices/:
This pull request updates all the documentation links in README to the working versions:
- https://panko.dev/performance/
- https://panko.dev/design-choices/
- https://panko.dev/
- https://panko.dev/getting-started/
=> Update invalid documentation links in README
